version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/http"
      - "/grpc"
      - "/aws"
      - "/tools"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"